

# try:
#     raise Exception("We can give the exception a message")

# except Exception as exc:
#     print("There was an exception: " + exc)

try:
    raise Exception("We can give the exception a message")

except Exception as exc:
    print("There was an exception: ", 1)

